- name: Install and Configure Cloudflared
  hosts: hpnodes
  become: true

  vars:
    cloudflared_version: "2024.6.0"
    clouflared_url: "https://github.com/cloudflare/cloudflared/releases/download/2024.6.0/cloudflared-linux-amd64.deb"

  tasks:
    - name: Ensure /etc/cloudflared/ exists
      ansible.builtin.file:
        path: /etc/cloudflared
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Download Cloudflared
      ansible.builtin.get_url:
        url: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
        dest: /tmp/cloudflared.deb
        mode: "0644"

    - name: Install Cloudflared
      ansible.builtin.apt:
        deb: /tmp/cloudflared.deb
        state: present

    - name: Copy config.yml
      ansible.builtin.template:
        src: files/config.yml.j2
        dest: /etc/cloudflared/config.yml
        owner: root
        group: root
        mode: "0644"

    - name: Copy Credentials File
      ansible.builtin.copy:
        src: files/{{ tunnel_id }}.json
        dest: /etc/cloudflared/{{ tunnel_id }}.json
        owner: root
        group: root
        mode: "0600"

    - name: Ensure systemd Service Exists
      ansible.builtin.copy:
        dest: /etc/systemd/system/cloudflared.service
        mode: "0644"
        content: |
          [Unit]
          Description=Cloudflare Tunnel
          After=network.target

          [Service]
          TimeoutStartSec=0
          Type=simple
          ExecStart=/usr/bin/cloudflared --no-autoupdate --config /etc/cloudflared/config.yml tunnel run

          [Install]
          WantedBy=multi-user.target

    - name: Reload System
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable Cloudflared at Boot
      ansible.builtin.systemd:
        name: cloudflared
        enabled: true
        state: started
