---
- name: Display facts returnet by module
  hosts: all
  gather_facts: false
  tasks:
    - name: Gathering services facts
      ansible.builtin.service_facts:

    - name: Debug
      ansible.buildin.debug: var=ansible_facts.services.ssh
...
