---
- name: Configure K3S worker nodes
  hosts: hpnodes_workers
  become: true
  roles:
    - python
    - base_system
    - shell_tools
    - monitoring_debug_tools
    - network_tools
    - postgres_client
