version: '3.9'

services:
  node1:
    image: ansible-node
    container_name: node1
    hostname: node1
    build:
      context: .
      dockerfile: Dockerfile.ansible-node
    ports:
      - "2221:22"

  node2:
    image: ansible-node
    container_name: node2
    hostname: node2
    build:
      context: .
      dockerfile: Dockerfile.ansible-node
    ports:
      - "2222:22"

  node3:
    image: ansible-node
    container_name: node3
    hostname: node3
    build:
      context: .
      dockerfile: Dockerfile.ansible-node
    ports:
      - "2223:22"
