FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openssh-server sudo python3 python3-pip && \
    useradd -m -s /bin/bash ansiblebot && \
    echo 'ansiblebot:ansiblebot' | chpasswd && \
    echo 'ansiblebot ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir /var/run/sshd

RUN mkdir -p /home/ansiblebot/.ssh

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
