FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openssh-server sudo python3 python3-pip vim && \
    useradd -m -s /bin/bash ansiblebot && \
    echo 'ansiblebot:ansiblebot' | chpasswd && \
    echo 'ansiblebot ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir /var/run/sshd

RUN mkdir -p /home/ansiblebot/.ssh

COPY authorized_keys /home/ansiblebot/.ssh/authorized_keys
COPY ./files/example.fact /etc/ansible/facts.d/example.fact

RUN chown -R ansiblebot:ansiblebot /home/ansiblebot/.ssh && \
    chmod 700 /home/ansiblebot/.ssh && \
    chmod 600 /home/ansiblebot/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
