- name: Deploy or update dev env
  hosts: node1hp
  become: true
  tasks:
    - name: Create folder for repo
      ansible.builtin.file:
        path: /home/ansiblebot/projects
        state: directory
        owner: ansiblebot
        group: ansiblebot
        mode: '0755'

    - name: Pull Repo
      ansible.builtin.git:
        repo: 'git@github.com:przemyslaw-koz/ansible-configs.git'
        dest: /home/ansiblebot/projects/ansible-configs
        version: main
        update: true
      become: false

    - name: Check if Dockerfile Changed
      ansible.builtin.shell: |
        set -euo pipefail
        git diff --name-only HEAD~1 HEAD | grep Dockerfile.ansible-node || true
      args:
        chdir: /home/ansiblebot/projects/ansible-configs
      register: dockerfile_diff
      changed_when: false

    - name: Rebuild Docker Image
      ansible.builtin.shell: |
        docker compose -f dev-env/docker-compose.yml build
      args:
        chdir: /home/ansiblebot/projects/ansible-configs/
      when: dockerfile_diff.stdout != ""
      changed_when: true

    - name: Check if Docker Compose Changed
      ansible.builtin.shell: |
        set -euo pipefall
        git diff --name-only HEAD~1 HEAD | grep docker-compose.yml || true
      args:
        chdir: /home/ansiblebot/projects/ansible-configs
      register: dockercompose_diff
      changed_when: false

    - name: Restart Docker Compose
      ansible.builtin.shell: |
        set -euo pipefall
        docker compose -f dev-env/docker-compose.yml down && \
        docker compose -f dev-env/docker-compose.yml up -d
      args:
        chdir: /home/ansiblebot/projects/ansible-configs
      when: dockerfile_diff.stdout != "" or dockercompose_diff.stdout != ""
      changed_when: true
